Algoritmo "a"
// 
//  
// Descrição   : Apresentar os quadrados dos números inteiros de 15 a 200
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 09/09/2021
Var
// Seção de Declarações das variáveis 
cont:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

para cont de 15 ate 200 passo 1 faca

Escreval(cont,"² = ",cont*cont)

fimpara


Fimalgoritmo