Algoritmo "b"
//
//
// Descrição   : Apresentar os resultados de uma tabuada de multiplicar (de 1 até 10) de um número qualquer
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 09/09/2021
Var
// Seção de Declarações das variáveis
j,v:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...

Escreval("Qual o numero que voce deseja saber")
leia(v)
para j de 1 ate 10 passo 1 faca

Escreval(v,"°",j," = ",v*j)

fimpara


Fimalgoritmo