Algoritmo "semnome"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 08/09/2021
Var
// Seção de Declarações das variáveis 
cont:inteiro


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

cont<-15
repita
Escreval("O valor de", cont, "*", cont, " = ", cont*cont)
cont<-cont+1
ate cont>200


Fimalgoritmo