Algoritmo "semnome"
//
//
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 08/09/2021
Var
// Seção de Declarações das variáveis
 i,x,r:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...

i<-1



repita

Escreval("Digite um valor para x")
leia(x)

r<-x*3
Escreval(" O valor de",x," * 3 é: ",r)

i<-i+1
ate i>5



Fimalgoritmo